version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: tekachi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - tekachi_db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tekachi-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      RFRSH_EXPIRATION: ${RFRSH_EXPIRATION}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    ports:
      - "8080:8080"

volumes:
  tekachi_db_data:
