spring.datasource.url=${TEKACHI_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=tekachi;encrypt=true;trustServerCertificate=true}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${TEKACHI_DB_USERNAME:sa}
spring.datasource.password=${TEKACHI_DB_PASSWORD:sa}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=245f99ebadb01b0dd4a7be0546098deaf89a9a12101745c140c27013edf3fb92
jwt.expiration=600000
jwt.rfrsh.expiration=86400000

openrouter.api.key=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

app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
